version: '3'
volumes:
  data-vol:

services:
  builder:
    build: builder
    volumes:
      - "data-vol:/opt/tomcat/latest/webapps"

  tomcat:
    build: service
    depends_on:
      - builder
    ports: 
      - "8080:8080"
    volumes:
       - "datavol:/opt/tomcat/webapps/"
#      - "data-vol:/opt/tomcat/apache-tomcat-9.0.46/webapps"
