version: '2.4'
services:
  builder:
    build: builder
    volumes:
      - data-vol:/opt

  tomcat:
    build: service
    ports: 
      - "8080:8080"
    volumes:
      - data-vol:/opt
volumes:
  data-vol: