version: '3'
services:
  builder:
    build: builder
    
    volumes:
      - data:/opt
    volumes_from:
      - php
  tomcat:
    build: service
    port: 8080:8080
    volumes:
      - data:/opt
  volumes:
    data: