version: '3'
volumes:
  builder:
  



services:
  builder:
    build: builder
    volumes:
      - "data-vol:/opt/test"

  tomcat:
    build: service
    ports: 
      - "8080:8080"
    volumes:
      - "data-vol:/opt/test"
