version: '3'
volumes:
  data-vol:

services:
  builder:
    build: builder
    volumes:
      - "data-vol:/opt/boxfuse"

  tomcat:
    build: service
    depends_on:
      - builder
    ports: 
      - "8080:8080"
    volumes:
      - "data-vol:/opt/test"
