version: '3'
volumes:
  data-vol:
    name: my-test-volume
    

services:
  builder:
    build: builder
    volumes:
      - "data-vol:/opt"

  tomcat:
    build: service
    ports: 
      - "8080:8080"
    volumes:
      - "data-vol:/opt"
